x-base-service: &base_service
  build:
    context: .
    args:
      DROPLET_IP: $DROPLET_IP
  network_mode: host
  environment:
    SSH_AUTH_SOCK: /ssh-agent
    NIXPKGS_ALLOW_BROKEN: 1
    NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
  volumes:
    - .:/workdir
    - $SSH_AUTH_SOCK:/ssh-agent
services:
  sh:
    <<: *base_service
    entrypoint: bash