x-base-service: &base_service
  build:
    context: .
  network_mode: host
  dns:
    - 8.8.8.8
    - 1.1.1.1
  environment:
    SSH_AUTH_SOCK: /ssh-agent
    NIXPKGS_ALLOW_BROKEN: 1
    NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
  env_file:
    - .env
  volumes:
    - .:/workdir
    - $SSH_AUTH_SOCK:/ssh-agent
    - nix-cache:/nix-cache

volumes:
  nix-cache: {}

services:
  sh:
    <<: *base_service
    entrypoint: bash
  gatus:
    image: twinproduction/gatus
    ports:
      - "8080:8080"
    volumes:
      - ./modules/gatus/config.yaml:/config/config.yaml
    env_file:
      - ./secrets/gatus.env
    environment:
      GATUS_LOG_LEVEL: DEBUG