version: "3"

vars:
  BUILD: .#nixosConfigurations.digitalOcean.config.system.build.digitalOceanImage
  CACHE: /nix-cache

tasks:
  deploy:
    desc: Deploy the NixOS image
    cmds:
      - deploy

  build:
    desc: Build the NixOS image
    cmds:
      - nix build ${BUILD} --system x86_64-linux

  cache:
    desc: Cache build products and dependencies
    cmds:
      - DERIVATION=$(nix path-info --derivation ${BUILD})
      - mapfile -t DEPENDENCIES < <(nix-store --query --requisites --include-outputs "${DERIVATION}")
      - printf '%s\n' "${DEPENDENCIES[@]}" | xargs nix copy --to "${CACHE}"

  upload:
    cmds:
      - doctl compute image create nix-image --region nyc1 --image-url "https://github.com/yurifrl/nixos/actions/runs/13526601851/artifacts/2650149472" --image-description "Custom nix image"