version: "3"

dotenv: [.env]

tasks:
  nix-build:
    desc: Build the NixOS image
    cmds:
      - nix build .#nixosConfigurations.digitalOcean.config.system.build.digitalOceanImage --system x86_64-linux

  nix-deploy:
    desc: Deploy the NixOS image
    cmds:
      - deploy path:.#

  load-envs:
    desc: Load environment variables
    cmds:
      - op inject -f -i .env.op -o .env

  cache:
    desc: Cache build products and dependencies
    cmds:
      - ./hack/cache.sh

  upload:
    cmds:
      - doctl compute image create nix-image --region nyc1 --image-url "https://github.com/yurifrl/nixos/actions/runs/13526601851/artifacts/2650149472" --image-description "Custom nix image"

  generate-known-hosts:
    desc: Generate known hosts file
    cmds:
      - ssh-keyscan -t ed25519 "{{.TAILSCALE_HOST}}" || true
      - ssh-keyscan -t ed25519 "{{.DROPLET_IP}}" || true
      - echo "add here https://github.com/yurifrl/nixos/settings/secrets/actions to DEPLOY_KNOWN_HOSTS"

  generate-deploy-keys:
    desc: Generate new SSH keys for deployment
    dir: ./secrets/deploy-key
    cmds:    
      - ssh-keygen -t ed25519 -C "github-actions-deploy" -f ./deploy-key -N ""
      - ssh-keyscan -t ed25519 "{{.TAILSCALE_HOST}}" > ./known_hosts
      - ssh-keyscan -t ed25519 "{{.DROPLET_IP}}" >> ./known_hosts
      - |
        # Generate known hosts file
        echo "Scanning hosts:"
        echo "âœ¨ Keys generated successfully!"
        echo ""
        echo "ðŸ”‘ Private Key (add to GitHub secret DEPLOY_SSH_KEY):"
        echo "----------------------------------------"
        cat ./deploy-key
        echo "----------------------------------------"
        echo ""
        echo "ðŸ” Public Key (add to NixOS config users/root.nix):"
        echo "----------------------------------------"
        cat ./deploy-key.pub
        echo "----------------------------------------"
        echo ""
        echo "ðŸŒ Known Hosts (add to GitHub secret DEPLOY_KNOWN_HOSTS):"
        echo "----------------------------------------"
        cat ./known_hosts
        echo "----------------------------------------"
        echo ""
        echo "All files saved in the ./secrets directory"
        echo "add here https://github.com/yurifrl/nixos/settings/secrets/actions to DEPLOY_SSH_KEY"

  load-build-secrets:
    desc: Load build secrets from the ./secrets directory
    cmds:
      - |
        echo "deploy.json" >> .git/info/exclude
        op read "op://kubernetes/nixos/deploy.json" -f -o deploy.json
        echo "deploy.json added to local git exclusion, (gambiarra to not commit deploy.json)"

  load-secrets:
    desc: Load secrets from the ./secrets directory
    dir: ./secrets
    cmds:
      - |
        op read "op://kubernetes/nixos/tailscale-auth.key" -f -o tailscale-auth.key
        op read "op://kubernetes/nixos/cloudflared-creds.json" -f -o cloudflared-creds.json
        op read "op://kubernetes/nixos/gatus.env" -f -o gatus.env

        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "mkdir -p /etc/tailscale /etc/cloudflared /etc/gatus"

        scp tailscale-auth.key {{.DROPLET_USER}}@{{.DROPLET_IP}}:/etc/tailscale/tailscale-auth.key
        scp cloudflared-creds.json {{.DROPLET_USER}}@{{.DROPLET_IP}}:/etc/cloudflared/config.json
        scp gatus.env {{.DROPLET_USER}}@{{.DROPLET_IP}}:/etc/gatus/gatus.env

        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "chmod 600 /etc/tailscale/tailscale-auth.key"
        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "chmod 600 /etc/cloudflared/config.json"
        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "chmod 600 /etc/gatus/gatus.env"

        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "chown -R tailscale:tailscale /etc/tailscale"
        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "chown -R gatus:gatus /etc/gatus"
        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "chown -R cloudflared:cloudflared /etc/cloudflared"

        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "cat /etc/tailscale/tailscale-auth.key"
        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "cat /etc/cloudflared/config.json"
        ssh {{.DROPLET_USER}}@{{.DROPLET_IP}} "cat /etc/gatus/gatus.env"
