version: "3"

dotenv: [.env]

vars:
  IMAGE: '{{.IMAGE | default "gatus"}}'
  BUMP_TYPE: '{{.BUMP_TYPE | default "patch"}}'
  PUSH: '{{.PUSH | default "true"}}'

tasks:
  deploy:
    desc: ðŸš€ Interactive release with beautiful TUI (charm-style CLI)
    cmds:
      - ./scripts/deploy

  release:
    desc: Non-interactive release (IMAGE=gatus|foundry BUMP_TYPE=patch|minor|major PUSH=true|false)
    cmds:
      - ./scripts/release.sh {{.IMAGE}} {{.BUMP_TYPE}} {{.PUSH}}

  nix:build:
    desc: Build both NixOS images (gatus and foundry)
    cmds:
      - task: nix:build:gatus
      - task: nix:build:foundry

  nix:build:gatus:
    desc: Build the Gatus monitoring image
    cmds:
      - nix build .#nixosConfigurations.gatus.config.system.build.digitalOceanImage --system x86_64-linux

  nix:build:foundry:
    desc: Build the Foundry VTT image
    cmds:
      - nix build .#nixosConfigurations.foundry.config.system.build.digitalOceanImage --system x86_64-linux

  nix:deploy:
    desc: Deploy both NixOS configurations (gatus and foundry)
    cmds:
      - deploy path:.#

  nix:deploy:gatus:
    desc: Deploy only Gatus configuration
    cmds:
      - deploy path:.#gatus

  nix:deploy:foundry:
    desc: Deploy only Foundry configuration
    cmds:
      - deploy path:.#foundry

  load:envs:
    desc: Load environment variables
    cmds:
      - op inject -f -i .env.op -o .env

  nix:cache:
    desc: Cache build products and dependencies
    cmds:
      - ./hack/cache.sh

  ssh:generate:
    desc: Generate new SSH keys for deployment
    dir: ./secrets/deploy-key
    cmds:
      - ssh-keygen -t ed25519 -C "github-actions-deploy" -f ./deploy-key -N ""
      - ssh-keyscan -t ed25519 "{{.TAILSCALE_HOST}}" > ./known_hosts
      - ssh-keyscan -t ed25519 "{{.DROPLET_IP}}" >> ./known_hosts
      - |
        echo "âœ¨ Keys generated successfully!"
        echo ""
        echo "ðŸ”‘ Private Key (add to GitHub secret DEPLOY_SSH_KEY):"
        echo "----------------------------------------"
        cat ./deploy-key
        echo "----------------------------------------"
        echo ""
        echo "ðŸ” Public Key (add to NixOS config users/root.nix):"
        echo "----------------------------------------"
        cat ./deploy-key.pub
        echo "----------------------------------------"
        echo ""
        echo "ðŸŒ Known Hosts (for reference):"
        echo "----------------------------------------"
        cat ./known_hosts
        echo "----------------------------------------"
        echo ""
        echo "ðŸ“ Add to: https://github.com/yurifrl/nixos/settings/secrets/actions"

  secrets:load:build:
    desc: Load build secrets (deploy.json from 1Password)
    cmds:
      - |
        echo "deploy.json" >> .git/info/exclude
        op read "op://kubernetes/nixos/deploy.json" -f -o deploy.json
        echo "âœ… deploy.json loaded"

  secrets:load:
    desc: Load all runtime secrets to both servers
    cmds:
      - task: secrets:load:gatus
      - task: secrets:load:foundry

  secrets:load:gatus:
    desc: Load Gatus server secrets
    dir: ./secrets
    cmds:
      - |
        echo "Loading secrets for Gatus server..."
        op read "op://kubernetes/nixos/tailscale-auth.key" -f -o tailscale-auth.key
        op read "op://kubernetes/nixos/gatus-cloudflared-creds.json" -f -o gatus-cloudflared-creds.json
        op read "op://kubernetes/nixos/gatus.env" -f -o gatus.env

        ssh {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}} "mkdir -p /etc/tailscale /etc/cloudflared /etc/gatus"

        scp tailscale-auth.key {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}}:/etc/tailscale/tailscale-auth.key
        scp gatus-cloudflared-creds.json {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}}:/etc/cloudflared/config.json
        scp gatus.env {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}}:/etc/gatus/gatus.env

        ssh {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}} "chmod 600 /etc/tailscale/tailscale-auth.key"
        ssh {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}} "chmod 600 /etc/cloudflared/config.json"
        ssh {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}} "chmod 600 /etc/gatus/gatus.env"

        ssh {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}} "chown -R tailscale:tailscale /etc/tailscale"
        ssh {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}} "chown -R gatus:gatus /etc/gatus"
        ssh {{.GATUS_DROPLET_USER}}@{{.GATUS_DROPLET_IP}} "chown -R cloudflared:cloudflared /etc/cloudflared"

        echo "âœ… Gatus secrets loaded successfully"

  secrets:load:foundry:
    desc: Load Foundry server secrets
    dir: ./secrets
    cmds:
      - |
        echo "Loading secrets for Foundry server..."
        op read "op://kubernetes/nixos/tailscale-auth.key" -f -o tailscale-auth.key
        op read "op://kubernetes/nixos/foundry-cloudflared-tunnel.json" -f -o foundry-cloudflared-tunnel.json
        op read "op://kubernetes/nixos/foundry-license.key" -f -o foundry-license.key
        op read "op://kubernetes/nixos/foundry-admin.key" -f -o foundry-admin.key

        ssh {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}} "mkdir -p /etc/tailscale /etc/cloudflared /etc/foundry"

        scp tailscale-auth.key {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}}:/etc/tailscale/tailscale-auth.key
        scp foundry-cloudflared-tunnel.json {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}}:/etc/cloudflared/foundry-tunnel.json
        scp foundry-license.key {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}}:/etc/foundry/license-key
        scp foundry-admin.key {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}}:/etc/foundry/admin-key

        ssh {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}} "chmod 600 /etc/tailscale/tailscale-auth.key"
        ssh {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}} "chmod 600 /etc/cloudflared/foundry-tunnel.json"
        ssh {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}} "chmod 600 /etc/foundry/license-key"
        ssh {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}} "chmod 600 /etc/foundry/admin-key"

        ssh {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}} "chown -R tailscale:tailscale /etc/tailscale"
        ssh {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}} "chown -R cloudflared:cloudflared /etc/cloudflared"
        ssh {{.FOUNDRY_DROPLET_USER}}@{{.FOUNDRY_DROPLET_IP}} "chown -R foundry:foundry /etc/foundry"

        echo "âœ… Foundry secrets loaded successfully"
