
version: "3"

tasks:
  build:
    cmds:
      - nix build .#nixosConfigurations.digitalOcean.config.system.build.digitalOceanImage

  upload:
    cmds:
      - doctl compute image create nix-image --region nyc1 --image-url "https://github.com/yurifrl/nixos/actions/runs/13526601851/artifacts/2650149472" --image-description "Custom nix image"