version: "3"

dotenv: [.env]

includes:
  nix: ./taskfiles/nix.yaml
  secrets: ./taskfiles/secrets.yaml
  ssh: ./taskfiles/ssh.yaml
  tf: ./taskfiles/terraform.yaml

tasks:
  release:
    desc: 🚀 Interactive release - beautiful TUI for version bumps + AI changelogs
    cmds:
      - ./scripts/release

  quick-release:
    desc: ⚡ Quick patch release - auto-bump patch version and push
    cmds:
      - ./scripts/release --quick
