apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: disabled      
  sources:
    - repoURL: https://github.com/yurifrl/home-systems.git
      targetRevision: HEAD
      path: k8s/charts/support
      helm:
        valuesObject:
          virtualServices:
            - name: jaeger
              service:
                name: jaeger-query
                namespace: monitoring
                port: 16686

    - repoURL: https://jaegertracing.github.io/helm-charts
      chart: jaeger
      targetRevision: "*"
      helm:
        valuesObject:
          provisionDataStore:
            cassandra: false
          storage:
            type: memory
          allInOne:
            enabled: true
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
          query:
            serviceType: ClusterIP
            ingress:
              enabled: false 
          service:
            annotations:
              teleport.dev/name: jaeger