services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - /uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yaml run
    volumes:
      - ./secrets/cloudflare.json:/etc/cloudflared/config.json
      - ./tunnel-config.yaml:/etc/cloudflared/config.yaml
    restart: always

  # tailscale:
  #   image: tailscale/tailscale:latest
  #   volumes:
  #     - tailscale:/var/lib/tailscale
  #   privileged: true
  #   env_file:
  #     - secrets/secrets.env
  #   environment:
  #     - TS_HOSTNAME=service-monitor
  #   restart: always