name: "Auto Tag on Version Change"

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different
    paths:
      - 'VERSION'  # Only trigger when VERSION file changes

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating tags
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Get Version
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Create Tag
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          # Check if tag already exists
          if ! git rev-parse "v$VERSION" >/dev/null 2>&1; then
            git tag "v$VERSION"
            git push origin "v$VERSION"
            echo "Created and pushed tag v$VERSION"
          else
            echo "Tag v$VERSION already exists, skipping"
          fi 